module.exports = {
  head1: {
    fontSize: 30,
    color: "black",
    textAlign: "center",
    fontWeight: "500",
  },
  head2: {
    fontSize: 20,
    color: "black",
    textAlign: "center",
  },
  formgroup: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    marginVertical: 8,
  },
  label: {
    fontSize: 14,
    color: "black",
    marginLeft: 10,
    marginBottom: 3,
  },
  input: {
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderColor: "black",
    borderWidth: 1,
  },
  link: {
    color: "#F50057",
    fontSize: 15,
  },

  text: {
    color: "grey",
    fontSize: 15,
    textAlign: "center",
    marginVertical: 10,
    marginBottom: 0,
  },
  link2: {
    color: "grey",
    fontSize: 15,
    textAlign: "center",
    marginVertical: 10,
  },
  link4: {
    color: "grey",
    fontSize: 15,
    textAlign: "center",
    marginBottom: 20,
  },
  link3: {
    color: "grey",
    fontSize: 15,
    textAlign: "center",
    marginTop: 4,
  },
  input1: {
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    height: 100,
    textAlignVertical: "top",
    borderColor: "black",
    borderWidth: 1,
  },
  errormessage: {
    color: "white",
    fontSize: 15,
    textAlign: "center",
    backgroundColor: "#F50057",
    padding: 5,
    borderRadius: 10,
  },
  bwmessage: {
    color: "white",
    backgroundColor: "black",
    fontSize: 15,
    textAlign: "center",
    padding: 5,
    borderRadius: 5,
  },
};
